### ISSUE TITLE
Unable to change year for some courses.

### ISSUE THREAD

**Issue by GraithTiger** [dannybd/courseroad#1]
Example majors/classes include 6.131,2.008,2.60,14.01

**Comment by dannybd** [comment]
Changing class years for all four examples is working for me; what OS/browser are you using?

Here's a test road with all four classes in it, with different majors chosen: https://courseroad.mit.edu/#NjMyN0

**Comment by GraithTiger** [comment]
Win7 Firefox 40 and 43 both have this issue.
To clarify, I am able to decrease the year, but I can neither see the dropdown or select years higher that '14-'15

Same issue on the test road.

**Comment by dannybd** [comment]
Ah, I see it now. A bunch of 2015-2016 versions of classes failed to import. I've flushed and repopulated CourseRoad's data from the Data Warehouse, and now all classes are accounted for and have their 2016 versions:

https://courseroad.mit.edu/#YWQ4M0

Thanks for catching this!
