### ISSUE TITLE
Login Not Working

### ISSUE THREAD

**Issue by vontell** [dannybd/courseroad#16]
Login is not working for me. Maybe this is because of the new Duo authentication?

**Comment by dannybd** [comment]
Have you tried refreshing your certificates at [ca.mit.edu](http://ca.mit.edu)? That's almost always the culprit. (CourseRoad doesn't use Touchstone or Duo auth, although it may in the future.)

Best,
Danny

**Comment by vontell** [comment]
Sorry about that; fixing the certs worked.
