### ISSUE TITLE
Enable subject selection from Course Requirements in sidebar

### ISSUE THREAD

**Issue by CodyMoose** [dannybd/courseroad#31]
While CourseRoad has made course selection and path planning far easier, one might be able to expedite the process by enabling the user to simply click a subject number in their Course's requirements and have that subject automatically pop up either arbitrarily in Freshman Fall, or potentially whatever the term selection dropdown is set to within the Add tab.

**Comment by dannybd** [comment]
Hi @CodyMoose—it's not particularly well-advertised, but you can drag those course numbers off of the list and drop them into the semester of your choice. Let me know if that's not working for you, and I'll reopen this issue. Thanks!
